export const workData = [
  {
    name: 'MULTITENANCY SEKOLAH',
    image: 'sekolah.jpg',
    type: 'School Website',
    divisi: 'Fullstack Developer | UI Designer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel multitenancy', 'jquery', 'scss'],
    link: 'https://schooltenancy.000webhostapp.com/',
    swiper: ['sekolah.jpg'],
  },
  {
    name: 'PGRI KABUPATEN PASURUAN',
    image: 'pgri.jpg',
    type: 'Company Profile',
    divisi: 'FrontEnd Developer | UI Designer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel', 'jquery', 'scss'],
    link: 'https://pgripasuruankab.or.id/',
    swiper: ['pgri.jpg'],
  },
  {
    name: 'DIGITAL MAGAZINE',
    image: 'nesfol1.jpg',
    type: 'MADIG - NESFOL PROJECT',
    divisi: 'Fullstack Developer | UI Designer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel-API', 'vue3', 'scss', 'javascript'],
    link: 'https://nesfol.netlify.app/',
    swiper: ['nesfol1.jpg', 'nesfol2.jpg', 'nesfol3.jpg'],
  },
  {
    name: 'UKK MUHAMMAD RIFALDI',
    image: 'ukk-1.jpg',
    type: 'UKK KASIR RESTAURANT',
    divisi: 'Fullstack Developer | UI Designer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel-APi', 'vue3', 'scss', 'javascript', 'bootstrap'],
    link: 'https://github.com/rifaldimuhammad/ukk',
    swiper: ['ukk-1.jpg', 'ukk-2.jpg', 'ukk-3.jpg', 'ukk-4.jpg'],
  },
]
