export const workData = [
  {
    name: 'MULTITENANCY SEKOLAH',
    image: 'sekolah.jpg',
    type: 'School Website',
    divisi: 'Fullstack Developer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel multitenancy', 'jquery', 'scss'],
    link: 'https://github.com/Koichiro12/multitenancy-sekolah',
    swiper: ['sekolah.jpg'],
  },
  {
    name: 'PGRI KABUPATEN PASURUAN',
    image: 'pgri.jpg',
    type: 'Company Profile',
    divisi: 'FrontEnd Developer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel', 'jquery', 'scss'],
    link: 'https://github.com/NailulIjlalHaq/company-profile-pgri-pasuruan',
    swiper: ['pgri.jpg'],
  },
  {
    name: 'DIGITAL MAGAZINE',
    image: 'nesfol1.jpg',
    type: 'Produk',
    divisi: 'Fullstack Developer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel api', 'vue3', 'scss', 'javascript'],
    link: 'https://github.com/rifaldimuhammad/madig-vue',
    swiper: ['nesfol1.jpg' , 'nesfol2.jpg', 'nesfol3.jpg'],
  },
  {
    name: 'LONDON MOSQUES',
    image: 'londonMosque.jpg',
    type: 'Mosques Website',
    divisi: 'FrontEnd Developer',
    desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor similique laborum optio architecto libero enim aliquam perferendis facilis amet sunt?',
    language: ['laravel ', 'scss', 'jquery'],
    link: '',
    swiper: ['londonMosque.jpg'],
  },
]
